In [2]:
#imports
from sqlalchemy import create_engine
from datetime import timedelta, datetime, tzinfo
from zipfile import ZipFile
import collections
import pandas as pd

In [4]:
#Kaggle DATAFRAME
gun_df = pd.read_csv("gun-violence-data_01-2013_03-2018.csv")

FileNotFoundError: File b'gun-violence-data_01-2013_03-2018.csv' does not exist

In [65]:
gun_df.head()

,incident_id,date,state,city_or_county,address,n_killed,n_injured,incident_url,source_url,incident_url_fields_missing,...,participant_age,participant_age_group,participant_gender,participant_name,participant_relationship,participant_status,participant_type,sources,state_house_district,state_senate_district
0,461105,2013-01-01,Pennsylvania,Mckeesport,1506 Versailles Avenue and Coursin Street,0,4,http://www.gunviolencearchive.org/incident/461105,http://www.post-gazette.com/local/south/2013/0...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||3::Male||4::Female,0::Julian Sims,NaN,0::Arrested||1::Injured||2::Injured||3::Injure...,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://pittsburgh.cbslocal.com/2013/01/01/4-pe...,NaN,NaN
1,460726,2013-01-01,California,Hawthorne,13500 block of Cerise Avenue,1,3,http://www.gunviolencearchive.org/incident/460726,http://www.dailybulletin.com/article/zz/201301...,False,...,0::20,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male,0::Bernard Gillis,NaN,0::Killed||1::Injured||2::Injured||3::Injured,0::Victim||1::Victim||2::Victim||3::Victim||4:...,http://losangeles.cbslocal.com/2013/01/01/man-...,62.0,35.0
2,478855,2013-01-01,Ohio,Lorain,1776 East 28th Street,1,3,http://www.gunviolencearchive.org/incident/478855,http://chronicle.northcoastnow.com/2013/02/14/...,False,...,0::25||1::31||2::33||3::34||4::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Male||1::Male||2::Male||3::Male||4::Male,0::Damien Bell||1::Desmen Noble||2::Herman Sea...,NaN,"0::Injured, Unharmed, Arrested||1::Unharmed, A...",0::Subject-Suspect||1::Subject-Suspect||2::Vic...,http://www.morningjournal.com/general-news/201...,56.0,13.0
3,478925,2013-01-05,Colorado,Aurora,16000 block of East Ithaca Place,4,0,http://www.gunviolencearchive.org/incident/478925,http://www.dailydemocrat.com/20130106/aurora-s...,False,...,0::29||1::33||2::56||3::33,0::Adult 18+||1::Adult 18+||2::Adult 18+||3::A...,0::Female||1::Male||2::Male||3::Male,0::Stacie Philbrook||1::Christopher Ratliffe||...,NaN,0::Killed||1::Killed||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://denver.cbslocal.com/2013/01/06/officer-...,40.0,28.0
4,478959,2013-01-07,North Carolina,Greensboro,307 Mourning Dove Terrace,2,2,http://www.gunviolencearchive.org/incident/478959,http://www.journalnow.com/news/local/article_d...,False,...,0::18||1::46||2::14||3::47,0::Adult 18+||1::Adult 18+||2::Teen 12-17||3::...,0::Female||1::Male||2::Male||3::Female,0::Danielle Imani Jameison||1::Maurice Eugene ...,3::Family,0::Injured||1::Injured||2::Killed||3::Killed,0::Victim||1::Victim||2::Victim||3::Subject-Su...,http://myfox8.com/2013/01/08/update-mother-sho...,62.0,27.0

In [77]:
#Cluster map DATAFRAME
gv_data_df = gun_df[['date','state','city_or_county','n_killed','n_injured','latitude','longitude','incident_url','source_url']].copy()
gv_data_df['date'] = gv_data_df['date'].astype(str)
gv_data_2018 = gv_data_df[(gv_data_df['date'] >= '2018-01-01') & (gv_data_df['date'] <= '2018-03-31')]
gv_data_2018_states = gv_data_2018.groupby('state')
deaths_2018 = gv_data_2018_states['n_killed','n_injured'].sum()
deaths_2018_unindexed = deaths_2018.reset_index()

In [86]:
#Bar chart DATAFRAME
date_df = gun_df.set_index("date")
##
date_df.sort_values(by=['date'], inplace=True, ascending=False)
data2017_df = date_df.loc['2017-12-31':'2017-01-01']
data2016_df = date_df.loc['2016-12-31':'2016-01-01']
data2015_df = date_df.loc['2015-12-31':'2015-01-01']
data2014_df = date_df.loc['2014-12-31':'2014-01-01']
##
trend_list = [{"year":"2017","injured": data2017_df["n_injured"].sum(), "killed":data2017_df["n_killed"].sum(),
              "guns_count":data2017_df["n_guns_involved"].sum() },
             {"year":"2016","injured": data2016_df["n_injured"].sum(), "killed":data2016_df["n_killed"].sum(),
              "guns_count":data2016_df["n_guns_involved"].sum() },
             {"year":"2015","injured": data2015_df["n_injured"].sum(), "killed":data2015_df["n_killed"].sum(),
              "guns_count":data2015_df["n_guns_involved"].sum() },
             {"year":"2014","injured": data2014_df["n_injured"].sum(), "killed":data2014_df["n_killed"].sum(),
              "guns_count":data2014_df["n_guns_involved"].sum() }]


trend_list
##
years_trend = pd.DataFrame.from_dict(trend_list)
years_trend

   year  injured  killed  guns_count
0  2017    30703   15511     76189.0
1  2016    30580   15066     53821.0
2  2015    26967   13484     36849.0
3  2014    23002   12557      7927.0

In [87]:
#Line chart DATAFRAME
data14to18_df = date_df.loc['2018-03-31':'2014-01-01']
resetindex14_df = data14to18_df.reset_index()
new_df = resetindex14_df[["date","n_killed","n_injured", "n_guns_involved"]]
permonth1418 = pd.DatetimeIndex(new_df.date).to_period("M") 
gun14_monthly =new_df.groupby(permonth1418).sum()
gun14_monthly.reset_index(inplace=True)
gun14_monthly.head()

      date  n_killed  n_injured  n_guns_involved
0  2014-01      1070       1875            406.0
1  2014-02       845       1223            317.0
2  2014-03      1007       1551            406.0
3  2014-04       979       1782            586.0
4  2014-05      1099       2100            429.0

In [61]:
#postgreSQL connection
rds_connection_string =  "postgres:spitfire1@localhost:5432/GUN_VIOLENCE_PROJECT" 
engine = create_engine(f'postgresql://{rds_connection_string}')

In [81]:
engine.table_names()

['gun_year', 'killings_injuries_2018']

In [82]:
#pushing Cluster,Bar,Line DATAFRAME to SQL
years_trend.to_sql(name='gun_year', con=engine, if_exists='replace', index=False)
deaths_2018_unindexed.to_sql(name='killings_injuries_2018', con=engine, if_exists='replace', index=False)

In [88]:
#Creating CSV's of Cluster,Bar,Line DATAFRAME
years_trend.to_csv('year_trend_gun.csv')
deaths_2018.to_csv('deaths_2018.csv')
gun14_monthly.to_csv("gun2014onwrd.csv")